### ISSUE TITLE
Create UI for calculator

### ISSUE THREAD

**Issue by netkex** [Six-SM/calculator#1]
* [x] поле для ввода запроса + считывание клавиатура
* [x] листинг запросов

В качестве фреймворка для написания UI предлагается использовать [compose-multiplatform](https://www.jetbrains.com/lp/compose-multiplatform/), а первую версию сделать декстопную.

**Comment by arnyyyyy** [comment]
oh Jesus я думала мы пишем под андроид...

**Comment by netkex** [comment]
Кажется там основная часть не должна отличаться. Но если уже есть приложение, то не надо что-то менять, я думаю
