### ISSUE TITLE
HTTP-router server

### ISSUE THREAD

**Issue by netkex** [Six-SM/calculator#2]
Написать общую обертку HTTP-сервера + обработку JSON'ов

**Comment by frungl** [comment]
Кажется нужно три запроса такого формата:

### Вычислить выражение
```
POST /api/calculate
Content-Type: application/json

{
  "expression": "533*30+239",
  "timestamp": "1694867562"
}
```
В ответе получим json с ответом в виде строки

### Получить историю
```
GET /api/history
Content-Type: application/json
```
В ответе получим json с историей запросов в формате:
```
[
    {
        "id": "1",
        "expression": "533*30+239",
    }, {
        "id": "2",
        "expression": "2+2*2",
    }
]
```

### Запрос времени в которое было вычислено выражение
```
GET /api/meta/{id}
Content-Type: application/json
```
В ответе получим json с timestamp'ом

**Comment by frungl** [comment]
Думаю ktor с kotlinx-serialization отлично подойдут для этого

**Comment by netkex** [comment]
Выглядит хорошо, но есть пара моментов, которые хочется немного уточнить. 

1. > "timestamp": "1694867562"

   Наверное лучше вычислять `timestamp` на сервере, так как тогда отпадает вопрос о синхронизации времени. 

2. В листинге стоит еще возвращать результат выражения и что-то вроде `error`, если была ошибка во время вычисления. 

3. Не уверен, что нужен отдельный запрос для метадаты. Думаю для листинга, достаточно только отсортировать список на стороне сервера по времени. 

С ktor и kotlinx-serialization согласен :)

**Comment by frungl** [comment]
> 1. > "timestamp": "1694867562"
>    
>    
>    Наверное лучше вычислять `timestamp` на сервере, так как тогда отпадает вопрос о синхронизации времени.

Да, в этом есть смысл, тогда в запросе будем просто выражение отправлять

> 2. В листинге стоит еще возвращать результат выражения и что-то вроде `error`, если была ошибка во время вычисления.

Я думал об этом, и не понимаю зачем так делать. Ведь тогда результат выражения будет пустой, и не понятно какой плюс даёт лишнее поле с ошибкой.

> 3. Не уверен, что нужен отдельный запрос для метадаты. Думаю для листинга, достаточно только отсортировать список на стороне сервера по времени.

Мне казалось, что от нас требовали запрос к серверу по клику, но если нет, то абсолютно согласен.

**Comment by netkex** [comment]
> Мне казалось, что от нас требовали запрос к серверу по клику, но если нет, то абсолютно согласен.

Согласен, что не очень понятно, что подразумевается под "кликабельным списком". В моем понимании, это скорее как в мобильном калькуляторе, когда ты кликаешь и в окошко подставляется результат из истории. Но думаю запрос по метадате точно излишнее :) 

> Ведь тогда результат выражения будет пустой, и не понятно какой плюс даёт лишнее поле с ошибкой.

Возможно, можно не делать дополнительное поле содержащее ошибку, а сделать единое поле `result`. Я скорее исходил из того, что если у нас есть результат, то мы точно должны его показывать при листинге. 

Второй вариант, выводить в истории только успешные запросы. Но чисто субъективно мне кажется это хуже, чем запрос с какой-нибудь пометкой `error`.

**Comment by frungl** [comment]
Как насчет такого?

### Вычислить выражение
```
POST /api/calculate
Content-Type: application/json

{
  "expression": "533*30+239",
}
```
В ответе получим json с ответом в виде строки

### Получить историю
```
GET /api/history
Content-Type: application/json
```
В ответе получим json с историей запросов в формате:
```
[
    {
        "expression": "533*30+239",
        "result": "...",
        "id": "...",
        "timestamp": "..."
    }, {
        "expression": "2+2*2",
        "result": "...",
        "id": "...",
        "timestamp": "..."
    }
]
```
